name: Deploy

on:
  push:
    branches: ['develop']
  pull_request: # <-- PR일 때 Actions가 실행되도록 이 줄이 반드시 필요합니다
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: unanbb
          destination-repository-name: deploy
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.head_commit.message || github.event.pull_request.title || 'Update from GitHub Actions' }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

      - name: Comment PR with Deployment Link
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            🚀 **배포가 완료되었습니다!**
            다음 링크에서 확인하실 수 있습니다:
            https://deploy-practice-psi.vercel.app
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
